version: "3"
services:
  db:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/clean-ts-api
      - PORT=3000
    ports:
      - 3000:3000